# Generated by Django 5.1 on 2024-10-04 20:04

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_address_line_1',
            field=models.CharField(default='Default Address Line 1', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='default_city',
            field=models.CharField(default='Default City', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='default_country',
            field=django_countries.fields.CountryField(default='EU', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='default_email',
            field=models.EmailField(default='Default Email', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='default_full_name',
            field=models.CharField(default='Default Full Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='default_phone_number',
            field=models.CharField(default='Phone Number', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='default_postal_code',
            field=models.CharField(default='Default Postal Code', max_length=20),
            preserve_default=False,
        ),
    ]
