# Generated by Django 5.1 on 2024-09-23 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0004_productvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_catalog.country'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='static/media/background-image.jpg', null=True, upload_to=''),
        ),
    ]
