# Generated by Django 4.2 on 2024-12-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0009_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams')], default='kg', max_length=2),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.DecimalField(decimal_places=2, help_text='Size of the product (use kg or g).', max_digits=6),
        ),
    ]
