# Generated by Django 4.2 on 2025-01-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0010_productvariant_unit_alter_productvariant_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='unit',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.DecimalField(decimal_places=2, help_text='Size of the product in kilograms. For grams, use decimal representation (e.g., 0.5 for 500g).', max_digits=6),
        ),
    ]
