# Generated by Django 4.2 on 2024-12-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paypal_payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
